#+TITLE:  Venkatesh Choppella Research
#+SETUPFILE: ../org-templates/level-1.org
#+AUTHOR:    Venkatesh Choppella
#+EMAIL:     venkatesh.choppella@iiit.ac.in

* Menu
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: menu
   :CUSTOM_ID: menu
 :END:
  - [[../index.org][home]]
  - [[../research/index.org][research]]
  - [[../teaching/index.org][teaching]]
  - [[../biography/index.org][biography]]
  - [[../contact/index.org][contact]]
  - [[../calendar/index.org][calendar]]

* Submenu
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: sub-menu
   :CUSTOM_ID: sub-menu-research
 :END:

 - [[#areas][research areas]]
 - [[#students][students]]
 - [[#projects][funded projects]]
# - [[#service][service]]
 - [[#biblio][bibliography]]

* Main
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: main
   :CUSTOM_ID: main
 :END:

* Areas of research
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: areas
   :CUSTOM_ID: areas
 :END:

 - Software Engineering and Formal Methods :: Concurrency
      control /cite{2018-arxiv-choppella-et-al,2018-afmss-sanjeev-et-al}, Distributed
      Model Checking\cite{Singla-et-al-2016}, Real Time
      Systems\cite{Adimoolam-Choppella-2013}, Software and Systems
      Engineering\cite{2019-isec-chaudhuri-et-al, 2018-isec-banerjee-et-al,2018-incose-natarajan-et-al},
      Human Computer
      Interaction\cite{zade-choppella-ihci-2012,zade-et-al-chi-2014},
      Workflows
      \cite{dinesh-choppella-iceg-2010,Choppella-icdcit-2011,goel-choppella-t4e-2012,Goel-Choppella-icegov-2013},
      Modeling of Web Services\cite{WSCL-2002}, Data
      Modeling\cite{choppella-sengupta-robertson-johnson-tr-2006,choppella-et-al-afm07}
      and Visual
      modeling\cite{Choppella-Pulijala-ModSym-2015} and
      Software
      Architectures\cite{brahmajosyula-choppella-wambse-2011,brahmajosyula-choppella-journal-2011}. Formal
      Methods for
      VLSI\cite{Rath-Choppella-Johnson-1995,Bose-Tuna-Choppella-FMCAD-1996}

 - Web Accessibility  ::
      Renarration and Semantic
      Web\cite{Aggarwal-2012,Dinesh-2012-AFR-2207016-2207030,Dinesh-2012-ATR-2207016-2207038,Gollapudi-Choppella-t4e-2013,Prasad-2014-ONA-2596695-2596711,Prasad-et-al-isec-2017,2017-iske-gollapudi-et-al},
      \cite{DBLP-conf-seke-SanagavarapuGCR17,2018-icdcit-Prasad-et-al,2018-isec-prasad-et-al},

 - Web Security :: 
      Browser-based security policies\cite{Alloy-Corp-Tech-2013,Telikicherla-Choppella-Bezawada-ICISS-2014,Telikicherla-2014-EDS-2593761-2593764,agrawall-et-al-isec-2017,telikicherla-et-al-icissp-2017,2017-ICISS-Agrawall-et-al}

 - Applications of ICT ::  E-Governance\cite{choppella-srivathsan-icegov-2009}.

 - Educational Technology and Computing Pedagogy :: Virtual
   Labs\cite{2018-icalt-kumar-et-al, 2018-icalt-swain-et-al, bandi-et-al-t4e-2011,khot-choppella-t4e-2011,choppella-et-al-t4e-2011},\cite{malini-et-al-t4e-2012,Chatterjee-et-al-t4e-2013,2014-t4e-choudhary-et-al,2014-t4e-agarwal-et-al,Kelkar-et-al-icalt-2015,Ahuja-et-al-icalt-2015},
   Authoring tools and
   environments\cite{naidu-et-al-t4e-2010,Choppella-t4e-tutorial-2010,khare-et-al-t4e-2012},
   Ontologies\cite{mavalankar-et-al-t4e-2015}.  Functional
   Programming\cite{choppella-et-al-t4e-2012,Choppella-et-al-2016},
   Algorithms and Discrete Dynamical
   Systems\cite{Manjula-et-al-t4e-2013}.


 - Compilers and Programming Languages :: Evaluation of RMI
      protocols\cite{Govindaraju-et-al-Supercomputing-2000},
      Algorithm Synthesis from Domain Specific
      Languages\cite{Krishnan-et-al-HiPC-2003,Bibireata-et-al-LCPC-2004,Krishnan-et-al-IPDPS-2004,Baumgartner-ieee-2005,Auer-MolPhysics-2006,Hartono-et-al-iccs-2006,krishnan-et-al-jpdc-2006}.
      Aspect-Oriented Programming\cite{1999-aop-patent}.
      Term Unification\cite{Choppella-Haynes-CADE-2003,Choppella-Haynes-IC-2005},
      Type Inference\cite{Choppella-Haynes-1995,Choppella-thesis-02,Choppella-IFL-2003}.

* Students
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: students
   :CUSTOM_ID: students
 :END:
** Current students

 - Amar Banerjee (PhD)  :: Capability composition for
      robotics and cyber-physical systems engineering.

 - Mrityunjay Kumar (PhD) :: Model Based design and
      implementation of Virtual Lab Experiments

 - Sai Gollapudi (PhD) ::  Semantic Style Sheets and Renarration

 - Soumya Maddala (MS by research) :: Ontology services for
      web accessibility

 - Adhish Singla (MS Dual Degree) ::
      Distributed Model Checking.  Supported by Hitachi India.
      (Co-advisor with Prof. Suresh Purini)

 - Arjun Sanjeev (BTech/Dual Degree) ::  Modular Control of
      concurrent processes.  Co-advisor: Prof. K Viswanath.

 - Krutam  Hathi (BTech/Dual Degree) :: Pedagogy-based
      Analytics for virtual labs

** Past research students

 - Akaash Agarwall (MS by research, Apr 2018) ::  
      + Thesis title: Application,  Modelling and
        Implementation of CORP
      + Current affiliation: Facebook, California


  - Krishna Chaitanya (MS by research, May 2016) :: 
     + Thesis title:  [[http://web2py.iiit.ac.in/research_centres/publications/view_publication/mastersthesis/407][Mitigating Web-borne Security Threats by Enhancing Browser Security Policies]]
     + Current affiliation:  Microsoft Hyderabad


  - Ankur Goel (MS by research, Apr 2016) ::  
     + Thesis title: [[http://web2py.iiit.ac.in/research_centres/publications/view_publication/mastersthesis/412][Specification and Modelling of Workflow Management Systems with State Based Access Control]]
     + Current Affiliation: Startup in Hyderabad


  - Himanshu Zade (MS by research, Apr 2015) :: 
     + Thesis title:  [[http://web2py.iiit.ac.in/research_centres/publications/view_publication/mastersthesis/336][Evolution of Mental Models of Interactive Machines: A Formal Approach]]
     + Current affiliation: Univ of Washington PhD programme


  - Santosh Aravind Adimoolam (MS by research Apr 2014) :: 
    + Thesis title:
      [[http://web2py.iiit.ac.in/research_centres/publications/view_publication/mastersthesis/300][Automata based abstraction of interval assumptions and bounded input linear systems for verification and controller synthesis]]
    + Co-advisor:  Prof. K Viswanath    
    + Financial Support:  Siemens R&D India.
    + Current affiliation: VERIMAG, France.


  - Deepti Aggarwal (MS by research, Nov 2013) :: 
    + Thesis title: [[http://web2py.iiit.ac.in/research_centres/publications/view_publication/mastersthesis/232][Exploring Crowdsourcing to PersonalizeWeb Experiences]]
    + Co-advisor:  Prof. Vasudeva Varma
    + Current affiliation: Univ of Melbourne

* Funded Projects
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: projects
   :CUSTOM_ID: projects
 :END:
 - 1. Virtual Labs, Phase II and III (co-PI) ::  
      2016-2020. Sponsor: MHRD, Govt. of India.  Consortium
      partners: IITs at Bombay Delhi, Guwahati Kanpur,
      Kharagpur, Roorkee, Amrita University, COE Pune,
      Dayalbagh University, NIT Surathkal.  Total Budget:
      Rs. 100 Crores for 5 years.

 - 2. State variable approach to the model-driven
   development of software for reactive systems (PI) ::
   2011-2013.  Sponsor: Siemens India, Bangalore.  Budget:
   Rs. 14 Lakhs.



 - 3. Distributed Model Checking :: (Co-PI) 2014-2016.
      Sponsor: Hitachi India Limited.  Budget: 15 Lakhs.


 - 4. Virtual Labs Phase I :: 2010-2014. Sponsor: Virtual
      Labs consortium under the Virtual Labs main phase
      project.  Budget: 3.3 Cr.

 - 5. European Commission Erasmus Mundus External
   Cooperation Window (co-PI) :: European Research and
   Educational Collaboration with Asia Project for Academic
   Mobility 2008-2009. http://www.mrtc.mdh.se/eureca/.
   Institute Coordinator for IIITMK.  Budget: 10,000 Euro.

 - 6. ISEA (PI) :: Ministry of Information Technology,
                   Government of India.  Information
                   Security Education and Awareness (ISEA)
                   2006-2009.  Principal Investigator at
                   Participating Institution IIITM-K.
                   Rs. 3L per annum.

 - 7. Government of Kerala (co-PI) ::  Police Portal for
      Community Interaction 2004-2005.  Budget Rs. 2.9L
      Co-investigator.

* COMMENT Academic and Professional Service
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: service
   :CUSTOM_ID: service
 :END:

  - Conference Programme Committees :: LATicE 2018, 2015,
       FORMABS 2016.  T4E 2016 (Publicity Chair), 2015 (PC
       Chair), 2014, 2013, 2012, 2011.  ICTEE 2012, CSEE&T
       2012, 2011.  ICDCIT 2018, 2012.  ISEC 2011.  ICEGOV
       2015, 2014, 2013, 2012, 2011, 2010.  WAMBSE
       2012, 2011.  Free S/W Free Society 2005.
       ADCOMM 2005.  PDCAT 2004.


  - Conference Organizing Committees :: WWW 2011, ICPC 2013,
       T4E 2015, 2012. 


  - Journal reviewer :: Formal Methods in System Design.
       Springer, 2010.  Journal of Parallel and Distributed
       Computing, Elsevier, 2008.  International Journal of
       Formal Computing, Springer 2008.


  - PhD Theses Examination Committee ::  IIT Bombay 2009.
       Amrita University 2011.  University of
       Behrampur, 2015.


  - Expert Reviewer :: 

       + DRDO Project on Formal Methods, RCI,
         Hyderabad 2016.

       + MHRD Digital Library Project for Govt. of Kerala,
         Trivandrum Kerala, 2010.

* COMMENT Recent talks
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: talks
   :CUSTOM_ID: talks
 :END:
 - 19th Feb 2017 ::  A Formal Model of web security showing
      malicious Cross Origin Requests and its mitigation
      using CORP.  3rd International Conference on
      Information on Systems, Security and Privacy, {ICISSP}
      2017.  Porto, Portugal. 

 - 10-12th May 2017 :: Virtual Labs on the College Cloud.  3
      day workshop at JUIT, Waknaghat, Himachal Pradesh.

* Bibliography
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: biblio
   :CUSTOM_ID: biblio
 :END:
# #+BIBLIOGRAPHY: ref plain rev option:-d  option:-r option:-revkeys option:-dl option:-nokeywords option:-noabstract
#+BIBLIOGRAPHY: all plain rev option:-d  option:-r option:-revkeys option:-dl option:-nokeywords option:-noabstract




