#+TITLE:  Venkatesh Choppella
#+SETUPFILE: ../org-templates/level-1.org
#+AUTHOR:    Venkatesh Choppella
#+EMAIL:     venkatesh.choppella@iiit.ac.in

* Menu
 :PROPERTIES:
   :html_container_class: menu
   :custom_id: menu
 :END:
  - [[../index.org][home]]
  - [[../research/index.org][research]]
  - [[../teaching/index.org][teaching]]
  - [[../biography/index.org][biography]]
  - [[../contact/index.org][contact]]
  - [[../calendar/index.org][calendar]]

* Submenu
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: sub-menu
   :CUSTOM_ID: sub-menu-research
 :END:

 - [[Curriculum Vitae][curriculum vitae]]
 - [[Short Bio][short bio]]

* Curriculum Vitae

 CV in [[./resume/short.pdf][pdf]].

* Short Bio
 :PROPERTIES:
   :HTML_CONTAINER_CLASS: areas
   :CUSTOM_ID: short-bio
 :END:

Venkatesh Choppella is Associate Professor of Software
Engineering at the International Institute of Information
Technology Hyderabad, India.  He was also associated with
Indian Institute of Information Technology and Management --
Kerala, Trivandrum (2003-2009) and the IIIT Bangalore
(2009-2010).

Venkatesh  holds a PhD. degree in Computer Science from Indiana
University, Bloomington, USA, and Bachelors and Masters
degrees from the Indian Institutes of Technology, Kanpur and
Madras, respectively.  He has held research and engineering
positions in Hewlett Packard, Xerox Palo Alto Research
Centre, Oak Ridge National Laboratory, and the Ohio State
University in the United States.

Venkatesh's current research interests are in formal methods
and software architectures.  In addition, he has an interest
in computer science education and FOSS-based educational
technology.  He has published over 75 research papers and
technical reports in the areas of computer science, software
engineering, educational technology and computer science
pedagogy.






* COMMENT Report of Activities at IIITM-K: Dec 2003 to May 2009

Available in [[./2008-review/report.pdf][pdf]].
