#+SETUPFILE: ../org-templates/level-1.org


* Semester courses
** Programming Languages

*** Principles of Programming Languages
    Monsoon of 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009
    (co-instructor with Prof. Vasudeva Varma). [[http://pascal.iiit.ac.in/~choppell/popl/][Course pages]].
*** Interpreters and Compilers
    Spring 2004, IIITM-K

** Mathematical theory of Programming Languages

*** Software Foundations
    Spring 2015 (co-instructor with Prof. Suresh Purini).
*** Semantics of Programming Languages
    Spring 2014, 2013
*** Topics in Programming Languages
    Spring 2012

** Web Technologies

*** IT Workshop 2
    Spring 2011, 2010 at IIITH.
*** Web Technologies (all at IIITM-K)
    Fall 2008 ([[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2008-2009-sem1-webtech/ay-2008-2009-sem1-webtech-feedback.pdf][feedback]]), 2007(course [[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2007-2008-sem1-webtech/course-feedback.pdf][feedback]] | [[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2007-2008-sem1-webtech/instr-feedback.pdf][instructor feedback]]),
    2006, ([[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2006-2007-sem1-webtech/course-feedback.pdf][course feedback]] | [[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2006-2007-sem1-webtech/instr-feedback.pdf][instructor feedback]] | [[http://pascal.iiit.ac.in/~choppell/teaching/courses/ay-2006-2007-sem1-webtech/report.html][course report
    byinstructor]]), Winter 2003.
*** Advanced Web Technologies
    Spring 2004, IIITM-K

** Introductory Programming for Post Graduates

*** Computer Problem Solving
    Monsoon 2015, IIIT Hyderabad
*** Programming Application Software
    Fall 2009, IIIT Bangalore

** Other courses

*** Data Structures and Algorithms
    Spring 2009, IIITM Kerala
*** Computational Biology
    Fall 2007, (co-instructor), IIITM-K
*** Scientific Computing
    Fall 2006 (co-instructor), IIITM-K
*** Database Systems
    Spring 2006, 2005 (co-instructor), IIITM-K
*** Mathematical Foundations of Information Technology
    Winter 2004, IIITM-K

* Short courses/workshops

** Building a web application from Ground Up to the Cloud
    3 week short course May 16th-Jun 4th 2016 for Virtual Labs summer
    interns at IIIT-H.
** Dynamical Systems, Automata and Functional Programming
    2 day short course at Goa University Academic Staff College (ASC)
    for college teachers. 13-14 Jan, 2014, Goa.
** Mapcode and Computer Problem Solving
    3 day short course for College Teachers at VNR Vignan Jyothi
    College, Hyderabad. May 27-29, 2013, Hyderabad. (co-instructor
    with Prof. KV Nori and Prof. K Swath).

** Practical Program Verification
    4 day short course under the Tata Excellence in Computer Science
    (TECS) Programme, TCS Hyderabad, 14-18th February, 2008 (Session
    on Day 1 on "Verification in the PVS theorem prover".)

** Principles of Programming for the Web
    11 day short course for Andhra Pradesh College Teachers under the
    Govt. India TEQIP Project organized by Enhance Edu. May 3-13,
    2010, IIIT Hyderabad.




